import type { Client, Invoice, Payment, Company, InvoicePreferences } from "@/types"

export const sampleCompany: Company = {
  id: "comp1",
  name: "Auto Repair Pro",
  address: "123 Workshop Lane, Garageville, 12345",
  phone: "+1 (555) 123-4567",
  email: "info@autorepairpro.com",
  logoUrl: "/placeholder.svg?height=100&width=100",
  ownerId: "user1",
}

export const sampleClients: Client[] = [
  {
    id: "client1",
    companyId: "comp1",
    name: "Alice Smith",
    address: "456 Oak Avenue, Townsville, 67890",
    phone: "+1 (555) 987-6543",
    email: "alice.smith@example.com",
    vehicleMake: "Honda",
    vehicleModel: "Civic",
    vehicleYear: 2018,
    licensePlate: "ABC-123",
    createdAt: "2023-01-15T10:00:00Z",
  },
  {
    id: "client2",
    companyId: "comp1",
    name: "Bob Johnson",
    address: "789 Pine Street, Cityburg, 10112",
    phone: "+1 (555) 234-5678",
    email: "bob.j@example.com",
    vehicleMake: "Ford",
    vehicleModel: "F-150",
    vehicleYear: 2020,
    licensePlate: "DEF-456",
    createdAt: "2023-02-20T11:30:00Z",
  },
  {
    id: "client3",
    companyId: "comp1",
    name: "Charlie Brown",
    address: "101 Maple Drive, Villageton, 34567",
    phone: "+1 (555) 876-5432",
    email: "charlie.b@example.com",
    vehicleMake: "Toyota",
    vehicleModel: "Camry",
    vehicleYear: 2015,
    licensePlate: "GHI-789",
    createdAt: "2023-03-01T09:15:00Z",
  },
]

export const sampleInvoices: Invoice[] = [
  {
    id: "inv1",
    companyId: "comp1",
    clientId: "client1",
    invoiceNumber: "INV-2023-001",
    date: "2023-03-01",
    dueDate: "2023-03-31",
    items: [
      { description: "Oil Change", quantity: 1, unitPrice: 50, total: 50 },
      { description: "Tire Rotation", quantity: 1, unitPrice: 30, total: 30 },
    ],
    subtotal: 80,
    taxPercentage: 10,
    taxAmount: 8,
    discountPercentage: 0,
    discountAmount: 0,
    totalAmount: 88,
    amountPaid: 88,
    status: "paid",
    notes: "Thank you for your business!",
    type: "invoice",
    createdAt: "2023-03-01T14:00:00Z",
  },
  {
    id: "inv2",
    companyId: "comp1",
    clientId: "client2",
    invoiceNumber: "INV-2023-002",
    date: "2023-03-05",
    dueDate: "2023-04-04",
    items: [
      { description: "Brake Pad Replacement (Front)", quantity: 1, unitPrice: 150, total: 150 },
      { description: "Brake Fluid Flush", quantity: 1, unitPrice: 75, total: 75 },
    ],
    subtotal: 225,
    taxPercentage: 10,
    taxAmount: 22.5,
    discountPercentage: 5,
    discountAmount: 11.25,
    totalAmount: 236.25 - 11.25, // Corrected total after discount
    amountPaid: 100,
    status: "pending",
    notes: "Customer requested premium brake pads.",
    type: "invoice",
    createdAt: "2023-03-05T10:00:00Z",
  },
  {
    id: "inv3",
    companyId: "comp1",
    clientId: "client1",
    invoiceNumber: "BL-2023-001",
    date: "2023-03-10",
    dueDate: "2023-03-10", // For Bon de Livraison, due date is usually same as date
    items: [
      { description: "Diagnostic Check", quantity: 1, unitPrice: 60, total: 60 },
      { description: "Battery Test", quantity: 1, unitPrice: 20, total: 20 },
    ],
    subtotal: 80,
    taxPercentage: 0,
    taxAmount: 0,
    discountPercentage: 0,
    discountAmount: 0,
    totalAmount: 80,
    amountPaid: 0,
    status: "pending", // BLs might not have payments directly
    notes: "Initial inspection for engine light.",
    type: "bon_de_livraison",
    createdAt: "2023-03-10T09:00:00Z",
  },
  {
    id: "inv4",
    companyId: "comp1",
    clientId: "client3",
    invoiceNumber: "INV-2023-003",
    date: "2023-03-15",
    dueDate: "2023-04-14",
    items: [
      { description: "Transmission Fluid Change", quantity: 1, unitPrice: 200, total: 200 },
      { description: "Spark Plug Replacement", quantity: 4, unitPrice: 25, total: 100 },
    ],
    subtotal: 300,
    taxPercentage: 10,
    taxAmount: 30,
    discountPercentage: 0,
    discountAmount: 0,
    totalAmount: 330,
    amountPaid: 0,
    status: "overdue",
    notes: "Major service performed.",
    type: "invoice",
    createdAt: "2023-03-15T16:00:00Z",
  },
]

export const samplePayments: Payment[] = [
  {
    id: "pay1",
    companyId: "comp1",
    invoiceId: "inv1",
    amount: 88,
    date: "2023-03-01",
    method: "Credit Card",
  },
  {
    id: "pay2",
    companyId: "comp1",
    invoiceId: "inv2",
    amount: 100,
    date: "2023-03-06",
    method: "Cash",
  },
]

export const samplePreferences: InvoicePreferences = {
  dateFormat: "YYYY-MM-DD",
  defaultTaxPercentage: 10,
  showDueDate: true,
  showTax: true,
  showDiscount: true,
  showNotes: true,
  language: "en",
}
